### ISSUE TITLE
Questions regarding annotation tool

### ISSUE THREAD

**Issue by SoniaQi** [mingliangzhang2018/PGDP#6]
Hi,

I attempted to run the demo with some additional images, but it appears that proper results are only generated when a file with image annotations is provided. Since your PGDP paper mentions your unique annotation method and the re-annotation of other datasets, could you please point me to the part of the code responsible for annotation?

Thank you very much for your assistance!

**Comment by mingliangzhang2018** [comment]
Hello, our annotation file only provides the OCR content of text because the PGDPNet  doesn't have the OCR ability. You could use OCR tools to generate bounding box and content of text, or leverage annotation  tools such as "labelme" and "labelimg" to label text content, then convert to the corresponding annotation format. I'm apologize that we have not built an end-to-end annotation tool yet.

**Comment by SoniaQi** [comment]
I see. Your response is much appreciated.
